config/routes.rb
AdjustedAssets::Application.routes.draw do

  resources :portfolios do
    resources :asset_actions
    resources :option_actions
  end

  resources :settings

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show

end

app/controllers/option_actions_controller.rb
class OptionActionsController < ApplicationController

  before_filter :get_portfolio
  
  # GET portfolios/1/option_actions
  # GET portfolios/1/option_actions.xml
  def index
    @option_actions = @portfolio.option_actions

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @option_actions }
    end
  end

  # GET portfolios/1/option_actions/new
  # GET portfolios/1/option_actions/new.xml
  def new
    @option_action = @portfolio.option_actions.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @option_action }
    end
  end

  # GET portfolios/1/option_actions/1/edit
  def edit
    @option_action = @portfolio.option_actions.find(params[:id])
  end

  # POST portfolios/1/option_actions
  # POST portfolios/1/option_actions.xml
  def create
    @option_action = @portfolio.option_actions.new(params[:option_action])

    respond_to do |format|
      if @option_action.save
        format.html { redirect_to(portfolio_option_actions_url(@portfolio), :notice => 'Option action was successfully created.') }
        format.xml  { render :xml => @option_action, :status => :created, :location => [@portfolio, @option_action] }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @option_action.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT portfolios/1/option_actions/1
  # PUT portfolios/1/option_actions/1.xml
  def update
    @option_action = @portfolio.option_actions.find(params[:id])
    respond_to do |format|
      if @option_action.update_attributes(params[:option_action])
        format.html { redirect_to(portfolio_option_actions_url(@portfolio), :notice => 'Option action was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @option_action.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE portfolios/1/option_actions/1
  # DELETE portfolios/1/option_actions/1.xml
  def destroy
    @option_action = @portfolio.option_actions.find(params[:id])
    @option_action.destroy

    respond_to do |format|
      format.html { redirect_to portfolio_option_actions_url(@portfolio) }
      format.xml  { head :ok }
    end
  end
  
  private

  def get_portfolio
    @portfolio = Portfolio.find(params[:portfolio_id])
  end
end

app/helpers/option_actions_helper.rb
module OptionActionsHelper
  def call_put_type(option)
    if option.is_call?
      "CALL"
    else
      "PUT"
    end
  end
  
  def expiration_dates
    exp_list = YAML::load(File.open("#{Rails.root}/config/expirations.yml"))
    collection = exp_list["TA25"].select{|d| d >= Date.today }.map {|d| [d.to_s(:expiration), d.to_s]}
  end
end

app/views/option_actions/_form.html.haml
= simple_form_for [@portfolio, @option_action] do |f|
  = f.error_notification

  .inputs
    = f.input :call_put, :label => "CALL/PUT", :collection => [["CALL", true], ["PUT", false]], :prompt => "Select Option Type"
    = f.input :strike, :collection => (800..1300).step(10), :selected => @option_action.strike || 1000
    = f.input :quantity, :hint => "number of stocks"
    = f.input :price, :hint => Money.default_currency.symbol, :label => "Price (per stock)"
    = f.input :exercise_date, :collection => expiration_dates, :prompt => "Select Expiration", :selected => expiration_dates.first
    
  .actions
    = f.button :submit

app/views/option_actions/edit.html.haml
- title "Editing Option Action"

= render 'form'

= link_to 'Back', portfolio_option_actions_path(@option_action.portfolio)

app/views/option_actions/index.html.haml
- title "Listing Option Actions"


%br
= link_to 'New Option Action', new_portfolio_option_action_path(params[:portfolio_id])
|
= link_to 'Portfolio', portfolio_path(@portfolio)
%br
%br
%table
  %tr
    %th Time Stamp
    %th Call/Put
    %th Strike
    %th Exercise Date    
    %th Quantity
    %th Price
    %th
    %th

  - @option_actions.each do |option_action|
    %tr
      %td= option_action.created_at.to_s(:time_stamp) unless option_action.created_at.blank?
      %td= call_put_type(option_action)
      %td= option_action.strike
      %td= option_action.exercise_date.to_s(:expiration)
      %td= option_action.quantity
      %td= option_action.price
      %td= link_to 'Edit', edit_portfolio_option_action_path(@portfolio, option_action)
      %td= link_to 'Destroy', [@portfolio, option_action], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Option Action', new_portfolio_option_action_path(params[:portfolio_id])
|
= link_to 'Portfolio', portfolio_path(@portfolio)

app/views/option_actions/new.html.haml
- title "New Option Action"

= render 'form'

= link_to 'Back', portfolio_option_actions_path(@portfolio)