config/routes.rb
AdjustedAssets::Application.routes.draw do

  resources :portfolios do
    resources :asset_actions
    resources :option_actions
  end

  resources :settings

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show

end

app/models/portfolio.rb
class Portfolio
  include Mongoid::Document
  field :name
  field :initial_investment, :type => Integer
  field :currency, :default => Money.default_currency.to_s
  field :created_at, :type => Date, :default => Time.now
  embeds_many :asset_actions
  embeds_many :option_actions
  embeds_many :money_transactions
  key :name

  validates :name, :presence => true, :uniqueness => true
  validates_numericality_of :initial_investment, :greater_than => 0
   
  def cash
    assets = asset_actions.inject(0) {|val, a| val - a.total_cost.cents}
    options = option_actions.inject(0) {|val, a| val - a.total_cost.cents}
    Money.new (100*self.initial_investment) + transactions_value + assets + options, self.currency 
  end

  def initial_money
    Money.new self.initial_investment*100, self.currency
  end
  
  def number_of_stocks
    asset_actions.sum(:quantity) || 0
  end
  
  def number_of_call_options
    number_of_options(true) || 0
  end
  
  def number_of_put_options
    number_of_options(false) || 0
  end
  
  def value(strike)
    step = 150
    if strike.class == Fixnum
      low = (strike-step)
      low = 0 if low < 0
      strike_range = low..(strike+step) 
    else
      strike_range = strike
    end
    strike_range.step(10).map do |strike|
      assets = asset_actions.inject(0) {|val, a| val + a.value_on_strike(strike)}
      options = option_actions.inject(0) {|val, o| val + o.total_exercise_value(strike).cents}
      value = assets + options/100
      [strike, value] 
    end
  end
  
  def cost
    assets = asset_actions.inject(0) {|val, a| val + a.price}
    options = option_actions.inject(0) {|val, o| val + o.price}
    assets + options
  end
  
  def transactions_value
    money_transactions.inject(0) {|val, t| val + t.value_cents}
  end
  
  def expire_options_by(date, strike)
    p_l = Money.new 0
    option_actions.each do |o|
      if o.is_expired?(date)
        p_l += o.total_exercise_value(strike)
      end
    end
    option_actions.where(:exercise_date.lte => date ).destroy
    money_transactions.create!(:value_cents => p_l.cents, :created_at => date, :note => "Options Expired")
  end
  
  private
  
  def number_of_options(call_put)
    option_actions.where(:call_put => call_put).sum(:quantity)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  before_filter :authorize, :except => [:index, :show] #TODO Add CanCan

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @portfolios }
    end
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @portfolio = Portfolio.find(params[:id])
    @current_strike = params[:strike] || '1000'
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/new
  # GET /portfolios/new.json
  def new
    @portfolio = Portfolio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/1/edit
  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(params[:portfolio])

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render json: @portfolio, status: :created, location: @portfolio }
      else
        format.html { render action: "new" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /portfolios/1
  # PUT /portfolios/1.json
  def update
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio.update_attributes(params[:portfolio])
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url }
      format.json { head :ok }
    end
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

  def is_new_object?(action)
    return ("new" == action)
  end
end

app/views/portfolios/edit.html.haml
- title "#{@portfolio.name}"

.h3 NOTHING EDIT YET! TBD

= link_to 'Show', @portfolio
\|
= link_to 'Back', portfolios_path

app/views/portfolios/index.html.haml
- title "Listing Portfolios"

%table
  %tr
    %th Name
    %th Stocks
    %th CALL
    %th PUT
    %th Initial Investment
    %th Cash
    %th Created at
    - if user_signed_in?
      %th
      %th

  - @portfolios.each do |portfolio|
    %tr
      %td= link_to portfolio.name, portfolio
      %td= portfolio.number_of_stocks
      %td= portfolio.number_of_call_options
      %td= portfolio.number_of_put_options
      %td= pretty_money(portfolio.initial_money, 0)
      %td= pretty_money(portfolio.cash, 0)
      %td= l portfolio.created_at, :format => :long
      - if user_signed_in?
        %td= link_to 'Edit', edit_portfolio_path(portfolio)
        %td= link_to 'Destroy', portfolio, :confirm => 'Are you sure?', :method => :delete

- if user_signed_in?
  %br
  = link_to 'New Portfolio', new_portfolio_path

app/views/portfolios/new.html.haml
- title "New Portfolio"

= simple_form_for(@portfolio) do |f|
  = f.error_notification

  .inputs
    = f.input :name
    = f.input :initial_investment, :hint => Money.default_currency.symbol

  .actions
    = f.button :submit

= link_to 'Back', portfolios_path

app/views/portfolios/show.html.haml
- title @portfolio.name

%p
  %b Number of stocks:
  = @portfolio.number_of_stocks
%p
  %b Number of CALL options:
  = @portfolio.number_of_call_options
%p
  %b Number of PUT options:
  = @portfolio.number_of_put_options  
%p
  %b Cash:
  = pretty_money(@portfolio.cash)
%p
  %b Created at:
  = @portfolio.created_at

- if user_signed_in?
  = link_to 'Assets', portfolio_asset_actions_path(@portfolio)
  \|
  = link_to 'Options', portfolio_option_actions_path(@portfolio)
  \| 
  = link_to 'Edit', edit_portfolio_path(@portfolio)
  \|
= link_to 'Back', portfolios_path
    
.row
  #chart

.row
  .span5.offset6
    - if (@current_strike.to_i - 100) > 0
      = link_to image_tag( 'go-previous-icon.png', :alt => "Move chart left", :title => "Move chart left", :class => 'bottom'), portfolio_path(@portfolio, :strike => (@current_strike.to_i - 100))
    %b= @current_strike
    = link_to image_tag( 'go-next-icon.png', :alt => "Move chart right", :title => "Move chart right", :class => 'bottom'), portfolio_path(@portfolio, :strike => (@current_strike.to_i + 100))

:javascript
  portfolio_value = #{@portfolio.value(@current_strike.to_i)};
  portfolio_symbol = "#{@portfolio.cash.symbol}"