config/routes.rb
AdjustedAssets::Application.routes.draw do

  resources :portfolios do
    resources :asset_actions
    resources :option_actions
  end

  resources :settings

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show

end

app/controllers/asset_actions_controller.rb
class AssetActionsController < ApplicationController

  before_filter :get_portfolio

  # GET /asset_actions
  # GET /asset_actions.json
  def index
    @asset_actions = @portfolio.asset_actions

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @asset_actions }
    end
  end

  # GET /asset_actions/new
  # GET /asset_actions/new.json
  def new
    @asset_action = @portfolio.asset_actions.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asset_action }
    end
  end

  # GET /asset_actions/1/edit
  def edit
    @asset_action = @portfolio.asset_actions.find(params[:id])
  end

  # POST /asset_actions
  # POST /asset_actions.json
  def create
    @asset_action = @portfolio.asset_actions.new(params[:asset_action])

    respond_to do |format|
      if @asset_action.save
        format.html { redirect_to portfolio_asset_actions_url(@portfolio), notice: 'Asset action was successfully created.' }
        format.json { render json: @asset_action, status: :created, location: [@portfolio, @asset_action] }
      else
        format.html { render action: "new" }
        format.json { render json: @asset_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /asset_actions/1
  # PUT /asset_actions/1.json
  def update
    @asset_action = @portfolio.asset_actions.find(params[:id])

    respond_to do |format|
      if @asset_action.update_attributes(params[:asset_action])
        format.html { redirect_to portfolio_asset_actions_url(@portfolio), notice: 'Asset action was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @asset_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asset_actions/1
  # DELETE /asset_actions/1.json
  def destroy
    @asset_action = @portfolio.asset_actions.find(params[:id])
    @asset_action.destroy

    respond_to do |format|
      format.html { redirect_to portfolio_asset_actions_url(@portfolio) }
      format.json { head :ok }
    end
  end

  private

  def get_portfolio
    @portfolio = Portfolio.find(params[:portfolio_id])
  end
end

app/helpers/asset_actions_helper.rb
module AssetActionsHelper
end

app/views/asset_actions/_form.html.haml
= simple_form_for [@portfolio, @asset_action] do |f|
  = f.error_notification

  .inputs
    = f.input :quantity, :hint => "number of stocks"
    = f.input :price, :hint => Money.default_currency.symbol, :label => "Price (per stock)"

  .actions
    = f.button :submit

app/views/asset_actions/edit.html.haml
- title "Editing Asset Action"

= render 'form'

= link_to 'Back', portfolio_asset_actions_path(@portfolio)

app/views/asset_actions/index.html.haml
- title "Listing Asset Actions"

%table
  %tr
    %th Quantity
    %th Price
    %th
    %th

  - @asset_actions.each do |asset_action|
    %tr
      %td= asset_action.quantity
      %td= pretty_money(asset_action.price)
      %td= link_to 'Edit', edit_portfolio_asset_action_path(@portfolio, asset_action)
      %td= link_to 'Destroy', [@portfolio, asset_action], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Asset Action', new_portfolio_asset_action_path(@portfolio)
|
= link_to 'Portfolio', portfolio_path(@portfolio)

app/views/asset_actions/new.html.haml
- title "New Asset Action"

= render 'form'

= link_to 'Back', portfolio_asset_actions_path