config/routes.rb
AdjustedAssets::Application.routes.draw do

  resources :portfolios do
    resources :asset_actions
    resources :option_actions
  end

  resources :settings

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show

end

app/models/setting.rb
class Setting
  include Mongoid::Document
  field :name, :unique => true
  field :multiplier, :type => Integer
  field :stock_fee, :type => Float
  field :option_fee, :type => Float
  field :supplement_stock, :type => Integer
  field :asset_adjustment, :type => Integer
  field :points_to_rehedge, :type => Integer
  
  validates :name, :presence => true, :uniqueness => true
  validates :multiplier, :presence => true
  validates :stock_fee, :presence => true
  validates :option_fee, :presence => true  
  validates :supplement_stock, :presence => true  
  validates :asset_adjustment, :presence => true  
  validates :points_to_rehedge, :presence => true      
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_filter :authorize, :except => [:index, :show]
  
  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
    @setting = Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/new
  # GET /settings/new.json
  def new
    @setting = Setting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(params[:setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render json: @setting, status: :created, location: @setting }
      else
        format.html { render action: "new" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:id])

    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.haml
= simple_form_for(@setting) do |f|
  = f.error_notification

  .inputs
    = f.input :name
    = f.input :multiplier
    = f.input :stock_fee
    = f.input :option_fee
    = f.input :supplement_stock
    = f.input :asset_adjustment, :hint => "%"
    = f.input :points_to_rehedge

  .actions
    = f.button :submit

app/views/settings/edit.html.haml
%h1 Editing setting

= render 'form'

= link_to 'Show', @setting
\|
= link_to 'Back', settings_path

app/views/settings/index.html.haml
- title "Listing Settings"

%table
  %tr
    %th Name
    %th Multiplier
    %th Stock fee
    %th Option fee
    %th Supplement stock
    %th Asset adjustment
    %th Points to rehedge
    - if user_signed_in?   
      %th
      %th

  - @settings.each do |setting|
    %tr
      %td= link_to setting.name, setting
      %td= setting.multiplier
      %td= setting.stock_fee
      %td= setting.option_fee
      %td= setting.supplement_stock
      %td= setting.asset_adjustment
      %td= setting.points_to_rehedge
      - if user_signed_in?    
        %td= link_to 'Edit', edit_setting_path(setting)
        %td= link_to 'Destroy', setting, :confirm => 'Are you sure?', :method => :delete

- if user_signed_in?
  %br
  = link_to 'New Setting', new_setting_path

app/views/settings/new.html.haml
- title "New setting"

= render 'form'

= link_to 'Back', settings_path

app/views/settings/show.html.haml
- title "Setting: #{@setting.name}" 

%p
  %b Multiplier:
  = @setting.multiplier
%p
  %b Stock fee:
  = @setting.stock_fee
%p
  %b Option fee:
  = @setting.option_fee
%p
  %b Supplement stock:
  = @setting.supplement_stock
%p
  %b Asset adjustment:
  = @setting.asset_adjustment
%p
  %b Points to rehedge:
  = @setting.points_to_rehedge

- if user_signed_in?
  = link_to 'Edit', edit_setting_path(@setting)
  \|
= link_to 'Back', settings_path